# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Dhrumil Patel
title: Data Scientist
email: dhrumilpatel02@gmail.com
website: dhrumilpatel02.github.io/portfolio/

# Social links
github_username: dhrumilpatel02
twitter_username: dhrumilpatel02
linkedin_username: dhrumilpatel02

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an experienced Data Scientist with a background in investment management. I've also worked with startups building machine learning models to help investors invest in the right ventures and building recommendation engines for news reading and posting. I've also briefly worked as a data science and analytics recruiter, recruiting data scientists for US clients.

  Skills: <mark>Python</mark>, <mark>R</mark>, <mark>SAS</mark>, <mark>SQL</mark>, <mark>Tableau</mark> and <mark>PowerBI</mark>

# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
