# Site
repository: sproogen/resume-theme
favicon: images/favicon_1.ico

# Personal info
name: HEET SONI
title: Data Analyst
email: soniheet6498@gmail.com
phone: +1 905-519-6464

# Social links
github_username: Heet6498
linkedin_username: heet-soni-379421104

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs


  I'm an experienced "Data Analyst". After completing my graduation in Information technology, I have decided to pursue my career in this booming data-driven industry as a data specialist. To reach my professional destination, I completed my two graduate certificates in "Data analytics for business marketing decisions" and in "Artificial intelligence". I have worked with startups, building analytics dashboards to help investors, and clients invest in the right ventures, building and presenting reports to the stakeholders. During my internship in SIC Technologies, I’ve also contributed my work to the Gujarat government (state of India) as a data analyst. 
  
  Skills: <mark>Python</mark>, <mark>SQL</mark>, <mark>Excel</mark>, <mark>PowerBI</mark>, and <mark>Tableau</mark>
  
# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Professional Certifications
more_content: | # this will include new lines to allow paragraphs
   - [Neural Networks and Deep Learning](https://www.coursera.org/account/accomplishments/verify/FHLAMKMBWZVK?utm_product=course)(deeplearning.ai)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
