# Site
repository: sproogen/resume-theme
favicon: images/favicon_1.ico

# Personal info
name: HEET SONI
title: Data Analyst
email: soniheet6498@gmail.com
phone: +1 905-519-6464

# Social links
github_username: Heet6498
linkedin_username: heet-soni-379421104

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an experienced Data Science and Analytics Professional and have worked with startups building analytics dashboards to help investors, and clients invest in the right ventures, building and presenting reports to the stakeholders. I've also briefly worked in the recruitment industry analyzing the trends in the US recruitment space. Currently, I am working to improve the overall content quality of the Catalogue at Cornershop with Data Science and Analytics tools and techniques.

  Skills: <mark>Python</mark>, <mark>SQL</mark>, <mark>Excel</mark>, <mark>PowerBI</mark>, <mark>Tableau</mark>, and <mark>PowerBI</mark>
  
# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Professional Certifications
more_content: | # this will include new lines to allow paragraphs
   - [Neural Networks and Deep Learning](https://www.coursera.org/account/accomplishments/verify/FHLAMKMBWZVK?utm_product=course)(deeplearning.ai)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
