# Site
repository: sproogen/resume-theme
favicon: images/Image.ico

# Personal info
name: HEET SONI
title: Data Analyst
email: soniheet6498@gmail.com
phone: +1 905-519-6464

# Social links
github_username: Heet6498
linkedin_username: heet-soni-379421104

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs


  I'm an experienced "Data Analyst" in this data-driven world. After completing my graduation in Information technology, I have decided to pursue my career in this booming data industry as a data specialist. To reach my professional destination, I completed my two graduate certificates in "Data analytics for business marketing decisions" and in "Artificial intelligence". I have worked with startups, building analytics dashboards to help investors, and clients invest in the right ventures, building and presenting reports to the stakeholders. During my internship in SIC Industries, I’ve also contributed my work to the Gujarat government (state of India) as a data analyst. 
  
  Skills: <mark>Python</mark>, <mark>SQL</mark>, <mark>Excel</mark>, <mark>PowerBI</mark>, and <mark>Tableau</mark>
  
# Experience Section
experience_title: Experience

# Projects Section
projects_title: Projects

# Education Section
educaton_title: Education

# More Section
more_title: Published Articles
more_content: | # this will include new lines to allow paragraphs
   - [A Guide to Data Standardization & Transformation](https://soniheet6498.medium.com/a-guide-to-data-standardization-transformation-1bf98d9b13b4)
   - [Automating Exploratory Data Analysis: Short cut to amazing initial data visualizations](https://soniheet6498.medium.com/automating-exploratory-data-analysis-short-cut-to-amazing-initial-data-visualizations-8d6002300277)
   - [VizWar: Comparison Between Visualization Platforms Such as Excel, Tableau, PowerBi, and Matplotlib/Seaborn](https://soniheet6498.medium.com/vizwar-%EF%B8%8F-comparison-between-visualization-platforms-such-as-excel-tableau-powerbi-and-577acf13c515)
   - [End to End Data Visualization Web-app Using Streamlit, From Data Scraping to Deployment](https://soniheet6498.medium.com/end-to-end-data-visualization-web-app-using-streamlit-from-data-scrapping-to-deployment-98beb963df57)
   -
   - [Neural Networks and Deep Learning](https://www.coursera.org/account/accomplishments/verify/FHLAMKMBWZVK?utm_product=course)(deeplearning.ai)
   
# More Section
more_title: Articles
more_content: | # this will include new lines to allow paragraphs
   - [Neural Networks and Deep Learning](https://www.coursera.org/account/accomplishments/verify/FHLAMKMBWZVK?utm_product=course)(deeplearning.ai)
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
